runners:
 example-runner:
  image: public.ecr.aws/y2s4f3y9/ubuntu-generic
jobs:   
 hello-world:
  resource_spec: micro
  runner: example-runner
  current_working_directory: ~/
  output:
   artifact:
    - hello.txt  
  steps:
   - run:
      name: Text Hello World
      command: echo "Hello World" 
      
workflows:
 hello-world-workflow:
  jobs:
   - hello-world
