runners:
 example-runner:
  image: ubuntu
jobs:   
 hello-world:
  resource_spec: micro
  runner: example-runner
  steps:
   - run:
      name: Hello World
      command: echo "Hello World" 
      
workflows:
 hello-world-workflow:
  jobs:
   - hello-world
